---
title: "analysis_thesis"
author: "Hitomi Kariya"
date: "3/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
library(tidyverse)
data <- read.csv("Hitomi_aggregV2.csv")
```

```{r}
# filtering the data to mammo_uptodate only
mammo <- data %>% filter(covariatename == "mammo_uptodate")

# filtering to mammo_uptodate_cont only
mammo_uptodate_cont <- mammo %>% filter (covariatevalue == 1 & screenarm == 0)

# the number of control women who were up to date for mammo
num_up_cont <- sum(mammo_uptodate_cont$Frequency)

# filtering to mammo_uptodate_int only
mammo_uptodate_int <- mammo %>% filter (covariatevalue == 1 & screenarm == 1)

# the number of intervention women who were up to date for mammo
num_up_int <- sum(mammo_uptodate_int$Frequency)

# filtering to control women only (except for 8)
mammo_cont <- mammo %>% filter  (covariatevalue == 0 | covariatevalue == 1) %>% filter(screenarm == 0)

# the total number of control women (except for 8)
num_total_cont <- sum(mammo_cont$Frequency)

# filtering to intervention women only (except for 8)
mammo_int <- mammo %>% filter  (covariatevalue == 0 | covariatevalue == 1) %>% filter(screenarm == 1)

# the total number of intervention women (except for 8)
num_total_int <- sum(mammo_int$Frequency)
```

```{r}
### proportion of the 12 months period observed

# Control: filtering to enrollafrand_m only in control
enroll_cont <- data %>% filter(covariatename == "enrollafrand_m") %>% filter(screenarm == 0)

# Control: filtering to enrollafrand_m = 12 only in control
enroll_cont_12 <- enroll_cont %>% filter(covariatevalue == 12)

### Control: proportion of the 12 months period observed in control
sum(enroll_cont_12$Frequency) / sum(enroll_cont$Frequency)

# Intervention: filtering to enrollafrand_m only in intervention
enroll_int <- data %>% filter(covariatename == "enrollafrand_m") %>% filter(screenarm == 1)

# Intervention: filtering to enrollafrand_m = 12 only in intervention
enroll_int_12 <- enroll_int %>% filter(covariatevalue == 12)

### Intervention: proportion of the 12 months period observed in intervention
sum(enroll_int_12$Frequency) / sum(enroll_int$Frequency)
```

```{r}
mammo_sub <- read.csv("mammo_thesis.csv")

glm(num_uptodate ~ num_total, offset = prop_12, data = mammo_sub, family = poisson(link = "identity"))

# recode arm: control = 0, intervention = 1
mammo_sub$arm <- ifelse(mammo_sub$arm == "control", 0, 1)
mammo_sub$arm <- as.factor(mammo_sub$arm)

mammo_sub$prop_up_total <- mammo_sub$num_uptodate/mammo_sub$num_total

glm(prop_up_total ~ arm, offset = prop_12, data = mammo_sub, family = poisson(link = "identity"))
```

> Outcome variable: 0 (not update) or 1 (update)
> Exposure variable: 0 (control) or 1 (intervention)
> Expand the data set 

> Discuss how to adjust for the covariates later